// <auto-generated />
namespace Racun_kec_test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pdv_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pdv_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201906161524349_pdv_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
